name: hookup4u
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_code_picker: ^2.0.2
  flutter_facebook_auth: ^4.1.1
  pin_code_fields: ^7.0.0
  #swipe_stack: 1.0.0
  #flutter_swiper: 1.1.6
  #geocoder: 0.2.1
  flutter_geocoder: ^0.2.2-nullsafety
  flutter_swiper_null_safety: ^1.0.2
  #swipable_stack: ^0.5.0

  intl: ^0.17.0
  firebase_auth: 3.0.1
  cloud_firestore: ^1.0.3
  # geolocator: ^6.1.13
  location: ^4.0.0  
  image_picker: ^0.7.5
  image_cropper: ^1.4.0
  firebase_storage: ^10.3.2
  path_provider:
  cached_network_image: ^3.0.0
  share: ^2.0.2
  firebase_messaging: 12.0.0
  flutter_webview_plugin: ^0.4.0
  in_app_purchase: 0.5.0
  rflutter_alert: ^2.0.0
  agora_rtc_engine: 5.2.0
  permission_handler: ^8.3.0
  flutter_ringtone_player: ^3.0.0
  shimmer: ^2.0.0
  #apple_sign_in: ^0.1.0
  url_launcher: ^6.0.4
  flutter_mapbox_autocomplete: ^2.0.0  
  # firebase_admob: ^0.11.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  easy_localization: ^3.0.0
  firebase_core: 1.19.2
  google_mobile_ads: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "asset/Icon/icon.png" 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - asset/auth/
   - asset/
   - asset/translation/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
